# Generated by Django 4.0.4 on 2022-06-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Голосователь', 'verbose_name_plural': 'Голосователи'},
        ),
    ]
